parameters:
  teknoo.east.symfony.listener.kernel.class: 'Teknoo\East\FoundationBundle\Listener\KernelListener'

services:
  #Symfony kernel event listener
  teknoo.east.symfony.listener.kernel:
    class: '%teknoo.east.symfony.listener.kernel.class%'
    arguments:
      - '@Teknoo\East\Foundation\Manager\ManagerInterface'
      - '@Teknoo\East\Foundation\Http\ClientInterface'
      - '@Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory'
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
