parameters:
  teknoo.east.symfony.router.class: 'Teknoo\East\FoundationBundle\Router\Router'
  teknoo.east.symfony.listener.kernel.class: 'Teknoo\East\FoundationBundle\Listener\KernelListener'

services:
  #Symfony router
  Teknoo\East\FoundationBundle\Router\Router:
    alias: 'Teknoo\East\Foundation\Router\RouterInterface'
    public: true

  Teknoo\East\Foundation\Router\RouterInterface:
    class: '%teknoo.east.symfony.router.class%'
    arguments:
      - '@router'
      - '@service_container'
    public: true

  #Symfony kernel event listener
  teknoo.east.symfony.listener.kernel:
    class: '%teknoo.east.symfony.listener.kernel.class%'
    arguments:
      - '@Teknoo\East\Foundation\Manager\ManagerInterface'
      - '@Teknoo\East\Foundation\Http\ClientInterface'
      - '@Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory'
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
