parameters:
  east.processor.class: 'Teknoo\East\Foundation\Processor\Processor'
  east.router.class: 'Teknoo\East\Foundation\Router\Router'
  east.manager.class: 'Teknoo\East\Foundation\Manager\Manager'
  east.controller.class: 'Teknoo\East\Foundation\Controller\Controller'
  east.listener.kernel.class: 'Teknoo\East\Foundation\Listener\KernelListener'

services:
  east.processor:
    class: '%east.processor.class%'
    arguments:
      - '@service_container'
      - '@logger'

  east.router:
    class: '%east.router.class%'
    arguments:
      - '@router'
      - '@east.processor'

  east.manager:
    class: '%east.manager.class%'
    calls:
      - ['registerRouter', ['@east.router']]

  #events
  east.listener.kernel:
    class: '%east.listener.kernel.class%'
    arguments:
      - '@east.manager'
      - '@sensio_framework_extra.psr7.http_foundation_factory'
      - '@sensio_framework_extra.psr7.http_message_factory'
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
