parameters:
  teknoo.east.processor.class: 'Teknoo\East\Foundation\Processor'
  teknoo.east.manager.class: 'Teknoo\East\Foundation\Manager'
  teknoo.east.symfony.prototype.client.class: 'Teknoo\East\FoundationBundle\Http\Client'
  teknoo.east.symfony.router.class: 'Teknoo\East\FoundationBundle\Router\Router'
  teknoo.east.symfony.listener.kernel.class: 'Teknoo\East\FoundationBundle\Listener\KernelListener'

services:
  #Standard East Processor
  teknoo.east.processor:
    class: '%teknoo.east.processor.class%'
    arguments:
      - '@logger'

  #Standard East manager
  teknoo.east.manager:
    class: '%teknoo.east.manager.class%'
    calls:
      - ['registerRouter', ['@teknoo.east.symfony.router']]

  #Symfony Client
  teknoo.east.symfony.prototype.client:
    class: '%teknoo.east.symfony.prototype.client.class%'
    argument:
      - '@sensio_framework_extra.psr7.http_foundation_factory'
    shared: false

  #Symfony router
  teknoo.east.symfony.router:
    class: '%teknoo.east.symfony.router.class%'
    arguments:
      - '@router'
      - '@teknoo.east.processor'

  #Symfony kernel event listener
  teknoo.east.symfony.listener.kernel:
    class: '%teknoo.east.symfony.listener.kernel.class%'
    arguments:
      - '@teknoo.east.manager'
      - '@teknoo.east.symfony.prototype.client'
      - '@sensio_framework_extra.psr7.http_message_factory'
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
